version: '3.1'
services:
  app:
    container_name: app-springboot-libreria
    image: app-springboot-libreria
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always